// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    DO: DurableObjectNamespace<import("./src/databases").ClientDatabase>
}
